"""Aura Dark theme."""

from themes.theme_model import Theme

AURA_DARK = Theme(
    name="aura_dark",
    display_name="Aura Dark",
    main_bg="#110f18",
    panel_bg="#15141b",
    fg_color="#edecee",
    fg_dim="#6d6d6d",
    selection_bg="#3d375e",
    hover_bg="#29263c",
    line_number_bg="#15141b",
    line_number_fg="#525156",
    caret_fg="#edecee",
    indent_guide="#584e70",
    tab_bg="#15141b",
    tab_active_bg="#15141b",
    tab_fg="#6d6d6d",
    tab_active_fg="#edecee",
    tree_bg="#15141b",
    tree_fg="#edecee",
    tree_selected_bg="#29263c",
    tree_modified_fg="#61ffca",
    tree_ignored_fg="#6d6d6d",
    accent_color="#a277ff",
    border_color="#3b334b",
    border_focus="#a277ff",
    sash_color="#110f18",
    term_cyan="#61ffca",
    chat_user_fg="#61ffca",
    chat_assistant_fg="#a277ff",
    ai_processing_color="#a277ff",
    syntax_keyword="#a277ff",
    syntax_string="#61ffca",
    syntax_comment="#6d6d6d",
    syntax_number="#00FFFF",
    syntax_function="#ffca85",
    syntax_class="#00FFFF",
    syntax_operator="#a277ff",
    syntax_keyword_control="#a277ff",
    syntax_variable="#edecee",
    syntax_string_escape="#ffca85",
    syntax_regex="#ff6767",
    syntax_doc_comment="#6d6d6d",
    syntax_constant="#00FFFF",
    syntax_boolean="#00FFFF",
    term_black="#15141b",
    term_bg="#15141b",
    term_fg="#edecee",
    term_red="#ff6767",
    term_green="#61ffca",
    term_yellow="#ffca85",
    term_blue="#00FFFF",
    term_magenta="#a277ff",
    term_white="#edecee",
)
