name: Build

on:
  push:

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - run: make lint-check

  test:
    runs-on: macos-latest
    needs: lint
    steps:
      - uses: actions/checkout@v6
      - uses: astral-sh/setup-uv@v7
      - run: make install-system-deps
      - run: make install-py
      - run: make test

